In [1]:
# special IPython command to prepare the notebook for matplotlib
%matplotlib inline

import pandas as pd
import pandasql as pdsql
import warnings
import numpy as np
warnings.filterwarnings('ignore')
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")
color = sns.color_palette()
pd.set_option("display.max_rows",999)
pd.set_option("display.max_columns", 999)

In [2]:
df = pd.read_csv(r'\\rmc.local\dfsroot\Marketing\SourceData\Mail files For Data Warehouse\582) 118639A_RMC_NB_7.0_Final_Mailfile.txt', 
                 sep='\t', na_values='.', encoding="ISO-8859-1", error_bad_lines=False, low_memory=False)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_') 
df['drop_date'] = pd.to_datetime(df['drop_date'],infer_datetime_format=True)
df['drop_date'] = df['drop_date'].astype(str)
df.head()

,filecode,batch,lettercd,fico,vantage,ss7,name,lname,fname,mname,sname,addr2,street,city,state,zip5,zip4,hhseqnumber,qseqnum,node_code,county,checkamount,checknumber,acctnum,check_routing_number,checkamount_spelledout,drop_date,closed_date,amt_id,amt_finan1,apr1,pmt_amt_1,num_pmt_1,fin_chg_1,tot_pmt_1,amt_given1,lproc_fee1,acq_chg_1,inhandchg1,prepaidfinchg,intsurchglen,int_to_lender,mntfeetol1,mo_inhandchg,faceamtloan,loanfee8,loanfee4,effective_rate,principal,lastpmtamt,numpmts_exceptlast,interest,branchnumber,branchcompany,branchstreetaddress,branchcity,branchstate,branchzip,branchphone,branchfax,branchmanager,branchsupervisor,branchstatevp,distance_to_branch,branchbunch,fico_25pt,finode_rank,finode_short,archsegrank,lco,n_timesmailed,equ_criteria_code,equ_sequence_num,equ_bni_score,equ_cma3912,equ_cma3379,equ_cma3135,equ_cma3111,equ_cma3858,equ_cma3422,equ_cma3001,equ_dob,equ_attribute_1,equ_attribute_2,equ_attribute_3,equ_attribute_4,equ_attribute_5,equ_attribute_6,equ_attribute_7,equ_attribute_8,equ_attribute_9,equ_attribute_10,equ_attribute_11,equ_attribute_12,equ_vantage,equ_ficov8nf,equ_numopenmortaccts,tu_consumer_id,tu_tueditseqnum,tu_permid,tu_score_attribute,tu_variable1,tu_variable2,tu_variable3,tu_variable4,tu_variable5,tu_variable6,tu_variable7,tu_variable8,tu_variable9,tu_variable10,tu_variable11,tu_variable12,tu_variable13,tu_variable14,tu_variable15,tu_variable16,tu_variable17,tu_birth_date,tu_scrfi01,tu_mtn001,tu_miliflag,tu_at31s,tu_at36s,tu_au25s,tu_au27s,tu_bc28s,tu_bc106s,tu_bi01s,tu_bi27s,tu_bi57s,tu_br32s,tu_br35s,tu_co02s,tu_co03s,tu_fi01s,tu_fi20s,tu_fi34s,tu_fr31s,tu_g001c,tu_g002s,tu_g002c,tu_g041s,tu_g041c,tu_g042c,tu_g043c,tu_g058s,tu_g093s,tu_g100s,tu_g102s,tu_g105s,tu_g106s,tu_g202a,tu_g205s,tu_g215a,tu_g215b,tu_g218b,tu_g219a,tu_g219d,tu_g222s,tu_g223s,tu_g227s,tu_g228s,tu_g313s,tu_g237s,tu_g241s,tu_g251b,tu_in06s,tu_in20s,tu_in28s,tu_in101s,tu_mt47s,tu_of06s,tu_of12s,tu_pb09s,tu_re09s,tu_re21s,tu_re35s,tu_rt06s,tu_s068a,tu_s068b,tu_s071a,tu_s071b,tu_s073a,tu_s073b,tu_s204a,tu_s208s,tu_st05s,tu_st06s,tu_st12s,tu_st29s,tu_atap01,tu_inap01,tu_g242f,tu_g242s,tu_g243f,tu_g243b,tu_agg101,tu_agg102,tu_agg103,tu_agg104,tu_agg105,tu_agg106,tu_agg107,tu_agg108,tu_agg109,tu_agg110,tu_agg111,tu_agg112,tu_agg201,tu_agg202,tu_agg203,tu_agg204,tu_agg205,tu_agg206,tu_agg207,tu_agg208,tu_agg209,tu_agg210,tu_agg211,tu_agg212,tu_agg501,tu_agg502,tu_agg503,tu_agg601,tu_agg602,tu_agg603,tu_agg905,tu_agg908,tu_trv01,tu_trv21,tu_trv22,tu_rvlr07,tu_walshr03,tu_paymnt02,tu_cv04,tu_cv16,tu_cv23,tu_cv24,tu_cv30,tu_rets904,tu_rvdex02,tu_rvdexq2,tu_attr021,tu_attr042,tu_attr043,tu_attr044,tu_attr045,tu_attr046,tu_attr047,tu_attr048,tu_attr037,tu_attr018,tu_attr017,tu_attr019,tu_scrg094,tu_pbm003,tu_attr026,tu_gnn002,tu_numinq12,unnamed:_260
0,TU,RSA,BZSC,692,659,5088144,Donald E. Kennedy,KENNEDY,DONALD,E,,,213 N. Valley Rd.,Landrum,SC,29356,1237,702519931,86123,01-NBCC-00A,,"2,400.00",1020032459,2079900585175,53101561,two thousand four hundred and 00/100,2018-08-15,09/17/2018,636,"2,400.00",44.00,133.23,30,"1,596.90","3,996.90","2,400.00",,,,,,,,,,,,44.00,,,,,143,Regional Finance,"3720 Boiling Springs Rd, Suite F",Boiling Springs,SC,29316-5760,(864) 599-9445,(864) 606-3810,Bruce Lee,Edith Bly,Scott Juvelier,14.785331,Main,675-699,15,675-699_01,4,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000000174,01,50002C67A2A8,533,0,0,000,D,0017,A,6,2002-03-01,000,000,000000000,,,000000000,000000000,000,000,1969-07-19,003,000,N,050,011,001,001,000010000,000,005,002,000000000,000009279,000009279,-01,-01,002,142,034,-01,-01,000,-01,004,-01,-01,-01,000,000,000,001,001,321,000003754,000001740,-04,-04,000,000,000,003,-01,-01,-01,-01,001,001,000,001,142,000134572,000096334,-01,001,001,-01,000,044,000005323,000,000,-04,-04,-04,-04,-04,-00000004,-04,-01,-01,-01,-01,000001740,000001416,-01,001,-01,-01,000106980,000104757,000096522,000098618,000097682,000082836,000083440,000084029,000085014,000085608,000086185,000086763,000148972,000140414,000130414,000134532,000130334,000114895,000114895,000114895,000114895,000114895,000114895,000114895,000009279,000009030,-00000002,000010000,000010000,-00000002,0091.55,000009279,999,-02,000,000,000,000,-06,001,000000278,000000000,999,-00000002,-02,-02,000,000,001,000,000,000,000,000,,000,000,000,000,,000,000,01,NaN
1,TU,RSA,BZAL,694,729,3480006,James B. Middleton,MIDDLETON,JAMES,B,,,12924 Highway 157,Florence,AL,35633,4518,704125587,126477,01-NBCC-00A,,"2,200.00",1060015652,8018011620,53101561,two thousand two hundred and 00/100,2018-08-15,09/17/2018,641,"2,200.00",34.98,128.72,24,889.28,"3,089.28","2,200.00",,,,,120.00,697.28,72.00,,,,,25.88,,,,,804,Regional Finance,"2801 Mall Road, Suite 9",Florence,AL,35630-1676,(256) 740-0611,(256) 712-2735,Megan Cummings,Ed Vandeveire,Heather Meares,10.450688,Main,675-699,15,675-699_01,10,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000000660,01,D006BB00C17F,669,0,0,000,D,0017,A,7,2013-12-02,000,000,000000000,,,000000000,000000000,000,000,1951-09-05,001,001,N,043,030,001,001,000002200,000,010,001,000000000,000001110,000001028,-01,-01,001,068,015,-01,000,000,000,002,000,000,000,000,000,000,022,-01,534,000001524,000000431,-04,-04,000,000,000,-02,-01,-03,-01,-01,000,-01,000,000,119,000027960,000005179,000,-01,-01,-01,000,066,000002025,000,000,-04,-04,-04,-04,-04,-00000004,-04,-01,-01,-01,-01,000001230,000000576,-01,000,-01,000,000011255,000011848,000012275,000012847,000013485,000014133,000012709,000014737,000014647,000014790,000015248,000015130,000035560,000035790,000035790,000035790,000035790,000035790,000030090,000035790,000035790,000035790,000035790,000035540,000002056,000002057,000001949,000002200,000002200,000002200,0091.85,000002081,999,000,000,002,000,000,-06,000,000000055,-00000002,999,000000617,087,005,000,000,000,000,000,000,000,000,,000,000,000,000,,000,000,00,NaN
2,TU,U1A,BZVA,650,635,4545172,Diana Q. Currie,CURRIE,DIANA,Q,,,16124 Kennedy St.,Woodbridge,VA,22191,4500,700279989,340426,03-NBCC-00A,,"2,550.00",1010047056,8018017353,53101561,two thousand five hundred fifty and 00/100,2018-08-15,09/17/2018,657,"2,550.00",43.97,141.51,30,"1,695.23","4,245.23","2,550.00",127.50,,,,,,,,,,,39.20,"2,677.50",141.44,29,,1213,Regional Finance,14516 Smoketown Rd,Woodbridge,VA,22192-4719,(703) 987-2069,(703) 956-5143,Greg Martin,Dawn Williams,Lee Wright,3.295883,Main,650-674,7,650-674_03,1,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000001145,01,F000553CE5FF,582,0,0,000,D,0017,A,0,1995-04-01,001,000,000000000,,,000000000,000000000,000,001,1964-10-22,004,001,N,075,001,002,002,000004100,001,001,001,000000000,000001563,000000852,-01,-01,003,127,091,100,000,000,000,002,000,000,000,001,000,000,010,-01,398,000001617,000000339,000,-01,000,000,000,002,-01,-01,-01,001,000,-01,000,001,127,000098523,000067294,000,000,001,-01,002,006,000008083,000,001,000,000,-01,000,-01,-00000001,-04,-01,-01,-01,-01,000004864,000001508,000,000,000,-01,000070590,000074367,000075540,000076622,000077904,000076560,000076351,000076936,000077979,000077921,000043730,000044452,000104084,000106723,000106723,000106723,000106723,000104084,000103084,000103084,000103084,000103084,000067937,000067937,000003477,000003394,000003381,000004100,000004100,000004100,0083.35,000003888,005,000,000,001,001,014,062,000,000000153,000000000,999,000000686,076,008,000,000,001,000,000,000,000,000,,000,000,000,000,,000,000,02,NaN
3,TU,RSA,BZGA,629,600,4500644,Saundra Davis Nixon,NIXON,SAUNDRA,DAVIS,,,74 Winward Way SE,Smyrna,GA,30082,1952,703275372,104763,04-NBCC-00A,COBB,"1,400.00",1090003417,8018012941,53101561,one thousand four hundred and 00/100,2018-08-15,09/17/2018,503,"1,400.00",35.17,116.69,15,350.35,"1,750.35","1,400.00",,,,92.21,,,45.00,,"1,705.35",48.00,44.21,10.00,,,,213.14,1103,Regional Finance,2768 Cumberland Blvd SE,Smyrna,GA,30080-3048,(678) 402-0989,(470) 203-6950,David Stephens,Mike Votava,Heather Meares,4.456369,Main,625-649,8,625-649_04,13,SmCC,0,,,,,,,,,,,,,,,,,,,,,,,,,,,0000001864,01,A099DF00EC62,761,0,0,000,D,0017,A,0,2005-09-22,000,003,000000000,,,000000000,000000000,000,003,1967-06-17,001,000,N,050,007,001,001,000004450,000,004,-03,-00000003,000003599,000001403,-01,-01,001,066,003,-01,-01,000,-01,003,-01,-01,-01,000,000,000,011,-01,363,000002245,000001036,000,000,000,000,000,003,001,-01,-01,-01,000,-01,001,001,250,000053895,000023451,-01,-01,-01,-01,010,001,000001840,001,003,003,000,000,000,000,-00000002,-04,-01,001,002,002,000001179,000000496,-01,000,-01,000,000021170,000020348,000020820,000021546,000021941,000039457,000040690,000040741,000040234,000040644,000035470,000034783,000049480,000048980,000048730,000048730,000048730,000070375,000069765,000069965,000070345,000070345,000064345,000064345,000004209,000003954,000004324,000004450,000004450,000004450,0093.54,000004324,001,000,000,002,000,003,037,000,000000207,000000384,999,000009831,026,042,000,000,002,000,000,000,000,000,,000,000,000,000,,000,000,01,NaN
4,TU,RSE,BZTX,670,664,8910770,Vanessa Isabel Ramirez Smith,RAMIREZ SMITH,VANESSA,ISABEL,,,2002 Redbud Ave.,Tyler,TX,75701,4611,707380001,221014,04-NBCC-00A,,"2,400.00",1030153905,2079900585188,53101561,two thousand four hundred and 00/100,2018-08-15,09/17/2018,640,"2,400.00",33.11,138.06,24,913.44,"3,313.44","2,400.00",,,,100.00,,,,,,,,29.73,,,,813.44,501,Regional Finance,2523 East 5th Street,Tyler,TX,75701-3544,(903) 526-2777,(903) 224-8045,Pablo Salazar-Lopez,Stephanie Drake,Michael Johnson,0.897863,Main,650-674,6,650-674_04,14,SmCC,0,,,,,,,,,,,,,,,,,,,,,,,,,,,0000002418,01,30D4A9004D03,868,0,0,002,D,0017,A,0,2011-03-07,000,003,000005050,,,000008721,000000000,000,005,1985-10-05,003,000,N,025,019,-06,-06,000017200,000,001,-03,-00000003,000001748,000000811,-01,-01,002,020,096,-01,-01,000,-01,003,-01,-01,-01,000,000,000,004,004,175,000016367,000000870,001,001,000,000,000,001,001,-01,-01,-01,003,001,000,001,131,000042194,000049368,-01,000,-03,-01,001,004,000000541,000,002,002,000,000,001,001,000001430,-04,-01,000,001,001,000000739,000000665,000,000,001,001,000052611,000053235,000054052,000054948,000032753,000032812,000004057,000003417,000032014,000030091,000029639,000029962,000061804,000059804,000059804,000059804,000034205,000034205,000013710,000013710,000033205,000026405,000023005,000023005,000003243,000003519,000004004,000017200,000015200,000015200,0022.78,000004597,999,000,000,001,001,002,037,004,000000074,-00000002,999,000000276,730,000,000,000,000,000,000,000,000,000,,000,000,000,000,,000,000,06,NaN

In [3]:
df.shape

(618865, 261)

In [4]:
df.drop_date.unique()

array(['2018-08-15'], dtype=object)

In [5]:
pysql = lambda q: pdsql.sqldf(q, globals())
str1 = """
  select *, 
    case when length(SS7) = 5 then '00'|| SS7 
         when length(SS7) = 6 then '0'|| SS7 
          else SS7 end as SSN7 
  from df a;
  """

df = pysql(str1)
df.head()

,filecode,batch,lettercd,fico,vantage,ss7,name,lname,fname,mname,sname,addr2,street,city,state,zip5,zip4,hhseqnumber,qseqnum,node_code,county,checkamount,checknumber,acctnum,check_routing_number,checkamount_spelledout,drop_date,closed_date,amt_id,amt_finan1,apr1,pmt_amt_1,num_pmt_1,fin_chg_1,tot_pmt_1,amt_given1,lproc_fee1,acq_chg_1,inhandchg1,prepaidfinchg,intsurchglen,int_to_lender,mntfeetol1,mo_inhandchg,faceamtloan,loanfee8,loanfee4,effective_rate,principal,lastpmtamt,numpmts_exceptlast,interest,branchnumber,branchcompany,branchstreetaddress,branchcity,branchstate,branchzip,branchphone,branchfax,branchmanager,branchsupervisor,branchstatevp,distance_to_branch,branchbunch,fico_25pt,finode_rank,finode_short,archsegrank,lco,n_timesmailed,equ_criteria_code,equ_sequence_num,equ_bni_score,equ_cma3912,equ_cma3379,equ_cma3135,equ_cma3111,equ_cma3858,equ_cma3422,equ_cma3001,equ_dob,equ_attribute_1,equ_attribute_2,equ_attribute_3,equ_attribute_4,equ_attribute_5,equ_attribute_6,equ_attribute_7,equ_attribute_8,equ_attribute_9,equ_attribute_10,equ_attribute_11,equ_attribute_12,equ_vantage,equ_ficov8nf,equ_numopenmortaccts,tu_consumer_id,tu_tueditseqnum,tu_permid,tu_score_attribute,tu_variable1,tu_variable2,tu_variable3,tu_variable4,tu_variable5,tu_variable6,tu_variable7,tu_variable8,tu_variable9,tu_variable10,tu_variable11,tu_variable12,tu_variable13,tu_variable14,tu_variable15,tu_variable16,tu_variable17,tu_birth_date,tu_scrfi01,tu_mtn001,tu_miliflag,tu_at31s,tu_at36s,tu_au25s,tu_au27s,tu_bc28s,tu_bc106s,tu_bi01s,tu_bi27s,tu_bi57s,tu_br32s,tu_br35s,tu_co02s,tu_co03s,tu_fi01s,tu_fi20s,tu_fi34s,tu_fr31s,tu_g001c,tu_g002s,tu_g002c,tu_g041s,tu_g041c,tu_g042c,tu_g043c,tu_g058s,tu_g093s,tu_g100s,tu_g102s,tu_g105s,tu_g106s,tu_g202a,tu_g205s,tu_g215a,tu_g215b,tu_g218b,tu_g219a,tu_g219d,tu_g222s,tu_g223s,tu_g227s,tu_g228s,tu_g313s,tu_g237s,tu_g241s,tu_g251b,tu_in06s,tu_in20s,tu_in28s,tu_in101s,tu_mt47s,tu_of06s,tu_of12s,tu_pb09s,tu_re09s,tu_re21s,tu_re35s,tu_rt06s,tu_s068a,tu_s068b,tu_s071a,tu_s071b,tu_s073a,tu_s073b,tu_s204a,tu_s208s,tu_st05s,tu_st06s,tu_st12s,tu_st29s,tu_atap01,tu_inap01,tu_g242f,tu_g242s,tu_g243f,tu_g243b,tu_agg101,tu_agg102,tu_agg103,tu_agg104,tu_agg105,tu_agg106,tu_agg107,tu_agg108,tu_agg109,tu_agg110,tu_agg111,tu_agg112,tu_agg201,tu_agg202,tu_agg203,tu_agg204,tu_agg205,tu_agg206,tu_agg207,tu_agg208,tu_agg209,tu_agg210,tu_agg211,tu_agg212,tu_agg501,tu_agg502,tu_agg503,tu_agg601,tu_agg602,tu_agg603,tu_agg905,tu_agg908,tu_trv01,tu_trv21,tu_trv22,tu_rvlr07,tu_walshr03,tu_paymnt02,tu_cv04,tu_cv16,tu_cv23,tu_cv24,tu_cv30,tu_rets904,tu_rvdex02,tu_rvdexq2,tu_attr021,tu_attr042,tu_attr043,tu_attr044,tu_attr045,tu_attr046,tu_attr047,tu_attr048,tu_attr037,tu_attr018,tu_attr017,tu_attr019,tu_scrg094,tu_pbm003,tu_attr026,tu_gnn002,tu_numinq12,unnamed:_260,SSN7
0,TU,RSA,BZSC,692,659,5088144,Donald E. Kennedy,KENNEDY,DONALD,E,,,213 N. Valley Rd.,Landrum,SC,29356,1237,702519931,86123,01-NBCC-00A,,"2,400.00",1020032459,2079900585175,53101561,two thousand four hundred and 00/100,2018-08-15,09/17/2018,636,"2,400.00",44.00,133.23,30,"1,596.90","3,996.90","2,400.00",,,,,,,,,,,,44.00,,,,,143,Regional Finance,"3720 Boiling Springs Rd, Suite F",Boiling Springs,SC,29316-5760,(864) 599-9445,(864) 606-3810,Bruce Lee,Edith Bly,Scott Juvelier,14.785331,Main,675-699,15,675-699_01,4,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000000174,01,50002C67A2A8,533,0,0,000,D,0017,A,6,2002-03-01,000,000,000000000,,,000000000,000000000,000,000,1969-07-19,003,000,N,050,011,001,001,000010000,000,005,002,000000000,000009279,000009279,-01,-01,002,142,034,-01,-01,000,-01,004,-01,-01,-01,000,000,000,001,001,321,000003754,000001740,-04,-04,000,000,000,003,-01,-01,-01,-01,001,001,000,001,142,000134572,000096334,-01,001,001,-01,000,044,000005323,000,000,-04,-04,-04,-04,-04,-00000004,-04,-01,-01,-01,-01,000001740,000001416,-01,001,-01,-01,000106980,000104757,000096522,000098618,000097682,000082836,000083440,000084029,000085014,000085608,000086185,000086763,000148972,000140414,000130414,000134532,000130334,000114895,000114895,000114895,000114895,000114895,000114895,000114895,000009279,000009030,-00000002,000010000,000010000,-00000002,0091.55,000009279,999,-02,000,000,000,000,-06,001,000000278,000000000,999,-00000002,-02,-02,000,000,001,000,000,000,000,000,,000,000,000,000,,000,000,01,None,5088144
1,TU,RSA,BZAL,694,729,3480006,James B. Middleton,MIDDLETON,JAMES,B,,,12924 Highway 157,Florence,AL,35633,4518,704125587,126477,01-NBCC-00A,,"2,200.00",1060015652,8018011620,53101561,two thousand two hundred and 00/100,2018-08-15,09/17/2018,641,"2,200.00",34.98,128.72,24,889.28,"3,089.28","2,200.00",,,,,120.00,697.28,72.00,,,,,25.88,,,,,804,Regional Finance,"2801 Mall Road, Suite 9",Florence,AL,35630-1676,(256) 740-0611,(256) 712-2735,Megan Cummings,Ed Vandeveire,Heather Meares,10.450688,Main,675-699,15,675-699_01,10,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000000660,01,D006BB00C17F,669,0,0,000,D,0017,A,7,2013-12-02,000,000,000000000,,,000000000,000000000,000,000,1951-09-05,001,001,N,043,030,001,001,000002200,000,010,001,000000000,000001110,000001028,-01,-01,001,068,015,-01,000,000,000,002,000,000,000,000,000,000,022,-01,534,000001524,000000431,-04,-04,000,000,000,-02,-01,-03,-01,-01,000,-01,000,000,119,000027960,000005179,000,-01,-01,-01,000,066,000002025,000,000,-04,-04,-04,-04,-04,-00000004,-04,-01,-01,-01,-01,000001230,000000576,-01,000,-01,000,000011255,000011848,000012275,000012847,000013485,000014133,000012709,000014737,000014647,000014790,000015248,000015130,000035560,000035790,000035790,000035790,000035790,000035790,000030090,000035790,000035790,000035790,000035790,000035540,000002056,000002057,000001949,000002200,000002200,000002200,0091.85,000002081,999,000,000,002,000,000,-06,000,000000055,-00000002,999,000000617,087,005,000,000,000,000,000,000,000,000,,000,000,000,000,,000,000,00,None,3480006
2,TU,U1A,BZVA,650,635,4545172,Diana Q. Currie,CURRIE,DIANA,Q,,,16124 Kennedy St.,Woodbridge,VA,22191,4500,700279989,340426,03-NBCC-00A,,"2,550.00",1010047056,8018017353,53101561,two thousand five hundred fifty and 00/100,2018-08-15,09/17/2018,657,"2,550.00",43.97,141.51,30,"1,695.23","4,245.23","2,550.00",127.50,,,,,,,,,,,39.20,"2,677.50",141.44,29,,1213,Regional Finance,14516 Smoketown Rd,Woodbridge,VA,22192-4719,(703) 987-2069,(703) 956-5143,Greg Martin,Dawn Williams,Lee Wright,3.295883,Main,650-674,7,650-674_03,1,SmCC,1,,,,,,,,,,,,,,,,,,,,,,,,,,,0000001145,01,F000553CE5FF,582,0,0,000,D,0017,A,0,1995-04-01,001,000,000000000,,,000000000,000000000,000,001,1964-10-22,004,001,N,075,001,002,002,000004100,001,001,001,000000000,000001563,000000852,-01,-01,003,127,091,100,000,000,000,002,000,000,000,001,000,000,010,-01,398,000001617,000000339,000,-01,000,000,000,002,-01,-01,-01,001,000,-01,000,001,127,000098523,000067294,000,000,001,-01,002,006,000008083,000,001,000,000,-01,000,-01,-00000001,-04,-01,-01,-01,-01,000004864,000001508,000,000,000,-01,000070590,000074367,000075540,000076622,000077904,000076560,000076351,000076936,000077979,000077921,000043730,000044452,000104084,000106723,000106723,000106723,000106723,000104084,000103084,000103084,000103084,000103084,000067937,000067937,000003477,000003394,000003381,000004100,000004100,000004100,0083.35,000003888,005,000,000,001,001,014,062,000,000000153,000000000,999,000000686,076,008,000,000,001,000,000,000,000,000,,000,000,000,000,,000,000,02,None,4545172
3,TU,RSA,BZGA,629,600,4500644,Saundra Davis Nixon,NIXON,SAUNDRA,DAVIS,,,74 Winward Way SE,Smyrna,GA,30082,1952,703275372,104763,04-NBCC-00A,COBB,"1,400.00",1090003417,8018012941,53101561,one thousand four hundred and 00/100,2018-08-15,09/17/2018,503,"1,400.00",35.17,116.69,15,350.35,"1,750.35","1,400.00",,,,92.21,,,45.00,,"1,705.35",48.00,44.21,10.00,,,,213.14,1103,Regional Finance,2768 Cumberland Blvd SE,Smyrna,GA,30080-3048,(678) 402-0989,(470) 203-6950,David Stephens,Mike Votava,Heather Meares,4.456369,Main,625-649,8,625-649_04,13,SmCC,0,,,,,,,,,,,,,,,,,,,,,,,,,,,0000001864,01,A099DF00EC62,761,0,0,000,D,0017,A,0,2005-09-22,000,003,000000000,,,000000000,000000000,000,003,1967-06-17,001,000,N,050,007,001,001,000004450,000,004,-03,-00000003,000003599,000001403,-01,-01,001,066,003,-01,-01,000,-01,003,-01,-01,-01,000,000,000,011,-01,363,000002245,000001036,000,000,000,000,000,003,001,-01,-01,-01,000,-01,001,001,250,000053895,000023451,-01,-01,-01,-01,010,001,000001840,001,003,003,000,000,000,000,-00000002,-04,-01,001,002,002,000001179,000000496,-01,000,-01,000,000021170,000020348,000020820,000021546,000021941,000039457,000040690,000040741,000040234,000040644,000035470,000034783,000049480,000048980,000048730,000048730,000048730,000070375,000069765,000069965,000070345,000070345,000064345,000064345,000004209,000003954,000004324,000004450,000004450,000004450,0093.54,000004324,001,000,000,002,000,003,037,000,000000207,000000384,999,000009831,026,042,000,000,002,000,000,000,000,000,,000,000,000,000,,000,000,01,None,4500644
4,TU,RSE,BZTX,670,664,8910770,Vanessa Isabel Ramirez Smith,RAMIREZ SMITH,VANESSA,ISABEL,,,2002 Redbud Ave.,Tyler,TX,75701,4611,707380001,221014,04-NBCC-00A,,"2,400.00",1030153905,2079900585188,53101561,two thousand four hundred and 00/100,2018-08-15,09/17/2018,640,"2,400.00",33.11,138.06,24,913.44,"3,313.44","2,400.00",,,,100.00,,,,,,,,29.73,,,,813.44,501,Regional Finance,2523 East 5th Street,Tyler,TX,75701-3544,(903) 526-2777,(903) 224-8045,Pablo Salazar-Lopez,Stephanie Drake,Michael Johnson,0.897863,Main,650-674,6,650-674_04,14,SmCC,0,,,,,,,,,,,,,,,,,,,,,,,,,,,0000002418,01,30D4A9004D03,868,0,0,002,D,0017,A,0,2011-03-07,000,003,000005050,,,000008721,000000000,000,005,1985-10-05,003,000,N,025,019,-06,-06,000017200,000,001,-03,-00000003,000001748,000000811,-01,-01,002,020,096,-01,-01,000,-01,003,-01,-01,-01,000,000,000,004,004,175,000016367,000000870,001,001,000,000,000,001,001,-01,-01,-01,003,001,000,001,131,000042194,000049368,-01,000,-03,-01,001,004,000000541,000,002,002,000,000,001,001,000001430,-04,-01,000,001,001,000000739,000000665,000,000,001,001,000052611,000053235,000054052,000054948,000032753,000032812,000004057,000003417,000032014,000030091,000029639,000029962,000061804,000059804,000059804,000059804,000034205,000034205,000013710,000013710,000033205,000026405,000023005,000023005,000003243,000003519,000004004,000017200,000015200,000015200,0022.78,000004597,999,000,000,001,001,002,037,004,000000074,-00000002,999,000000276,730,000,000,000,000,000,000,000,000,000,,000,000,000,000,,000,000,06,None,8910770

In [6]:
cols = ["checkamount"]
df[cols] = df[cols].replace({'\$': '', ',': ''}, regex=True)
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [7]:
df.to_csv(r'C:\Users\cepps\RMC\Mail Files\R_data_objects\nb_cc\mb_nbcc_0582.txt', sep = '\t', mode='w', date_format='%Y%m%d')

In [8]:
str1 = """
select '104' as mon_ind,
       '02.NBCC' as camp_type,
       'NBCC_0818__Aug-18_Drop-1' as camp_type1,
       SS7 as ss7, 
       Drop_Date as drop_date, 
       FName as name, 
       STREET as street, 
       ZIP5 as zip5, 
       fico, 
       Apr1 as apr,
       CheckAmount as offer_amount, 
       state, 
       BranchNumber as branchnumber 
from df;
"""

mb_nbcc = pysql(str1)
mb_nbcc.head()

,mon_ind,camp_type,camp_type1,ss7,drop_date,name,street,zip5,fico,apr,offer_amount,state,branchnumber
0,104,02.NBCC,NBCC_0818__Aug-18_Drop-1,5088144,2018-08-15,DONALD,213 N. Valley Rd.,29356,692,44.00,2400.0,SC,143
1,104,02.NBCC,NBCC_0818__Aug-18_Drop-1,3480006,2018-08-15,JAMES,12924 Highway 157,35633,694,34.98,2200.0,AL,804
2,104,02.NBCC,NBCC_0818__Aug-18_Drop-1,4545172,2018-08-15,DIANA,16124 Kennedy St.,22191,650,43.97,2550.0,VA,1213
3,104,02.NBCC,NBCC_0818__Aug-18_Drop-1,4500644,2018-08-15,SAUNDRA,74 Winward Way SE,30082,629,35.17,1400.0,GA,1103
4,104,02.NBCC,NBCC_0818__Aug-18_Drop-1,8910770,2018-08-15,VANESSA,2002 Redbud Ave.,75701,670,33.11,2400.0,TX,501

In [9]:
mb_nbcc.shape

(618865, 13)

In [10]:
mb_nbcc.to_csv(r'C:\Users\cepps\RMC\Mail Files\R_data_objects\nb_cc\mb_nbcc_ALL.txt', sep = '\t', mode='a')

In [11]:
mb_nbcc = pd.read_csv(r'C:\Users\cepps\RMC\Mail Files\R_data_objects\nb_cc\mb_nbcc_ALL.txt', 
                 sep='\t', na_values='.', encoding="ISO-8859-1", error_bad_lines=False, low_memory=False)
mb_nbcc.columns = mb_nbcc.columns.str.strip().str.lower().str.replace(' ', '_')
mb_nbcc = mb_nbcc.replace(r'\s+', np.nan, regex=True)
#mb_nbcc = mb_nbcc.drop(['unnamed:_0'], axis=1)
mb_nbcc.head()

,mon_ind,camp_type,camp_type1,ss7,drop_date,name,street,zip5,fico,apr,offer_amount,state,branchnumber
1.0,81,02.NBCC,NBCC_0916__Sep-16,120256,2016-09-02,BRENT,NaN,87114,589,58.99,"1,000.00",NM,1005
2.0,81,02.NBCC,NBCC_0916__Sep-16,9011271,2016-09-02,THOMAS,NaN,88011,603,50.99,"1,400.00",NM,1001
3.0,81,02.NBCC,NBCC_0916__Sep-16,4580756,2016-09-02,KATHRYN,NaN,88240,615,50.99,"1,400.00",NM,1011
4.0,81,02.NBCC,NBCC_0916__Sep-16,5395176,2016-09-02,TRACY,NaN,87120,622,50.99,"1,400.00",NM,1004
5.0,81,02.NBCC,NBCC_0916__Sep-16,5402113,2016-09-02,LOUIS,NaN,88130,731,43.99,"1,800.00",NM,1010

In [12]:
mb_nbcc.shape

(11970721, 13)

In [13]:
mb_nbcc.describe(include = 'all')

,mon_ind,camp_type,camp_type1,ss7,drop_date,name,street,zip5,fico,apr,offer_amount,state,branchnumber
count,11970721,11970721,11970721,11970721,11970721,11934802,8,11967146,11970721,11722839,11967146,11967146,11967146
unique,23,2,31,3823582,32,205222,4,4153,177,74,48,10,354
top,94,02.NBCC,NBCC_0718__Jul-18_Drop-1,5257206,2018-07-16,MICHAEL,street,79936,674,33.1,2400,TX,1108
freq,1134249,11970718,710000,27,710000,157404,3,31434,222489,1898897,1359916,4769191,203643

In [14]:
mb_nbcc["camp_type1"].value_counts()

NBCC_0718__Jul-18_Drop-1         710000
NBCC_0717__Jul-17_Drop-2         630634
NBCC_0618__Jun-18_Drop-1         620000
NBCC_0818__Aug-18_Drop-1         618865
NBCC_1017__Oct-17_Drop-2         603031
NBCC_0817__Aug-17_Drop-1         600233
NBCC_0518__May-18_Drop-1         600000
NBCC_0917__Sep-17_Drop-2         556297
NBCC_1016__Oct-16                555264
NBCC_1017__Oct-17_Drop-1         531218
NBCC_0617__June-17_Drop-2        527525
NBCC_1117__Nov-17_Drop-1         516537
NBCC_1116__Nov-16_Drop-1         450000
NBCC_0118__Jan-18_Drop-1         440000
NBCC_0617__June-17_Drop-1        415106
NBCC_0418__Apr-18_Drop-2         408575
NBCC_0517__May-17                401319
NBCC_0317__April-17_Drop-1       341976
NBCC_0417__April-17_Drop-2       326992
NBCC_0117__Jan-17_Drop-1         300000
NBCC_0218__Jan-18_Drop-2         275000
NBCC_0117__Jan-17_Drop-2         250000
NBCC_0418__Apr-18_Drop-1         229000
NBCC_0318__Mar-18_Drop-1         225000
NBCC_0218__Feb-18_Drop-1         223289
NBCC_0217__Feb-17_Drop-1         206000
NBCC_0317__March-17_Feb_Drop2    200000
NBCC_0916__Sep-16                110699
NBCC_1216__Nov-16_Drop-2          80000
NBCC_0417__April-17_Drop-2_OK     18158
camp_type1                            3
Name: camp_type1, dtype: int64

In [15]:
mb_nbcc.groupby(["drop_date", "camp_type1"]).size().reset_index(name="count")

     drop_date                     camp_type1   count
0   2016-09-02              NBCC_0916__Sep-16   15053
1   2016-09-07              NBCC_0916__Sep-16   95646
2   2016-10-10              NBCC_1016__Oct-16  555264
3   2016-11-07       NBCC_1116__Nov-16_Drop-1  450000
4   2016-11-28       NBCC_1216__Nov-16_Drop-2   80000
5   2017-01-03       NBCC_0117__Jan-17_Drop-1  300000
6   2017-01-25       NBCC_0117__Jan-17_Drop-2  250000
7   2017-02-16       NBCC_0217__Feb-17_Drop-1  206000
8   2017-03-10  NBCC_0317__March-17_Feb_Drop2  200000
9   2017-04-03     NBCC_0317__April-17_Drop-1  341976
10  2017-04-25     NBCC_0417__April-17_Drop-2  326992
11  2017-04-28  NBCC_0417__April-17_Drop-2_OK   18158
12  2017-05-17              NBCC_0517__May-17  401319
13  2017-06-08      NBCC_0617__June-17_Drop-1  415106
14  2017-06-30      NBCC_0617__June-17_Drop-2  527525
15  2017-07-24       NBCC_0717__Jul-17_Drop-2  630634
16  2017-08-15       NBCC_0817__Aug-17_Drop-1  600233
17  2017-09-08       NBCC_0917__Sep-17_Drop-2  556297
18  2017-10-02       NBCC_1017__Oct-17_Drop-1  531218
19  2017-10-25       NBCC_1017__Oct-17_Drop-2  603031
20  2017-11-15       NBCC_1117__Nov-17_Drop-1  516537
21  2018-01-02       NBCC_0118__Jan-18_Drop-1  440000
22  2018-01-24       NBCC_0218__Jan-18_Drop-2  275000
23  2018-02-15       NBCC_0218__Feb-18_Drop-1  223289
24  2018-03-09       NBCC_0318__Mar-18_Drop-1  225000
25  2018-04-02       NBCC_0418__Apr-18_Drop-1  229000
26  2018-04-24       NBCC_0418__Apr-18_Drop-2  408575
27  2018-05-22       NBCC_0518__May-18_Drop-1  600000
28  2018-06-19       NBCC_0618__Jun-18_Drop-1  620000
29  2018-07-16       NBCC_0718__Jul-18_Drop-1  710000
30  2018-08-15       NBCC_0818__Aug-18_Drop-1  618865
31   drop_date                     camp_type1       3